spring:
  application:
    name: address
  flyway:
    baseline-on-migrate: true
    enabled: true
    location: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/address
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
          provider:
            github:
              authorization-uri: https://github.com/login/oauth/authorize
              token-uri: https://github.com/login/oauth/access_token
              user-info-uri: https://api.github.com/user
              user-name-attribute: id

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    redis:
      enabled: true
    mongodb:
      enabled: true
springdoc:
  swagger-ui:
    path: /

app:
  security-ignore:
    actuatorHealth: /actuator/health
    actuatorHealthDetails: /actuator/health/**
    swagger: /swagger-ui/**
    apiDocs: /v3/api-docs
    apiDocsDetails: /v3/api-docs/**
    address: /address/**